### ISSUE TITLE
Onzo unit crashing after a number of reads

### ISSUE THREAD

**Issue by pierz** [ep1cman/PyOnzo#2]
I've been testing it out on my Onzo unit and have managed to get it to read data on MacOS and on a Raspberry Pi, but after a short while (after 11-40 queries) when running your `read.py` script the Onzo unit seems to crash [screen goes blank] (and then reboots again) - with error below (but I guess the crash means that the `read()` fails...). I've checked to see if it correlates with battery or reactive power read but it doesn't appear do so, I also changed the read timeout but that doesn't seem to help. I was wondering if you might have any ideas as to how to fix it?

> Traceback (most recent call last):
>   File "read.py", line 17, in <module>
>     p_real = clamp.get_power()
>   File "/home/pi/PyOnzo.git/onzo/device.py", line 180, in getter
>     return self.get_register(register_name)
>   File "/home/pi/PyOnzo.git/onzo/device.py", line 133, in get_register
>     val = (val << 16) + self.get_register(addr)
>   File "/home/pi/PyOnzo.git/onzo/device.py", line 128, in get_register
>     resp_parser=parser)
>   File "/home/pi/PyOnzo.git/onzo/device.py", line 106, in _send_request
>     response = self.conn.message_receive()
>   File "/home/pi/PyOnzo.git/onzo/device.py", line 80, in message_receive
>     frame = bytes(self.dev.read(64, timeout))
>   File "hid.pyx", line 122, in hid.device.read
> OSError: read error

**Comment by ep1cman** [comment]
Hi,
This is not something I ever encountered when testing my unit. I've had it running for weeks at a time without the device crashing (at least I never observed a crash).

The cause of the error above is likely the device disconnecting when it crashes and therefore the script fails to read from it.

A few things that come to mind:
 - Have you tried using a different USB cable, it could just a broken cable
 - Does this happen on both MacOS and the Raspberry Pi or is it platform specific?
 - Are you running it with batteries installed? Might be worth trying with just USB power if you are.
- Something you could try is reducing the polling period by adjusting the sleep duration in read.py.

**Comment by leachj** [comment]
Thanks for this great library, it enabled me to get onzo integrated into home-assistant. 

However i've got the same issue with my Onzo unit as mentioned above. I'm running it straight from USB with no batteries and it fails after less than 24 hours with a 30 second polling interval. Any other ideas what might be happening or how to work around this?
